artifacts_root: artifacts

dataset:
  root_dir: artifacts/dataset
  source_URL: s3://quickgist/quickgist dataset.zip
  s3_bucket: quickgist
  s3_dataset: quickgist dataset.zip
  local_data_file: artifacts/dataset/dataset.zip
  unzip_dir: artifacts/dataset

