artifacts_root: artifacts

dataset:
  root_dir: artifacts/dataset
  source_URL: s3://quickgist/quickgist dataset.zip
  s3_bucket: quickgist
  s3_dataset: quickgist dataset.zip
  local_data_file: artifacts/dataset/dataset.zip
  unzip_dir: artifacts/dataset

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_DATASET_FILES: ["train.csv", "test.csv", "validation.csv"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/dataset/cnn_dailymail
  tokenizer_name: google/pegasus-cnn_dailymail

